// ExportButton.jsx — Month 28: Export reports to PDF & Excel
// Uses browser-native PDF print + SheetJS-style CSV (no CDN needed for basic)
import { useState } from 'react';

// ── CSV/Excel export (pure JS, no dependency) ─────────────────────────────
function exportCSV(filename, headers, rows) {
  const esc = (v) => {
    const s = String(v ?? '');
    return s.includes(',') || s.includes('"') || s.includes('\n')
      ? `"${s.replace(/"/g, '""')}"` : s;
  };
  const lines = [headers.map(esc).join(','), ...rows.map(r => r.map(esc).join(','))];
  const blob = new Blob([lines.join('\n')], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a'); a.href = url; a.download = filename; a.click();
  URL.revokeObjectURL(url);
}

// ── HTML → PDF via print dialog ───────────────────────────────────────────
function exportPDF(title, htmlContent) {
  const win = window.open('', '_blank');
  win.document.write(`<!DOCTYPE html><html><head>
    <title>${title}</title>
    <meta charset="utf-8"/>
    <style>
      * { margin: 0; padding: 0; box-sizing: border-box; }
      body { font-family: 'Segoe UI', sans-serif; font-size: 13px; color: #111; padding: 32px; }
      h1 { font-size: 22px; font-weight: 700; margin-bottom: 4px; color: #1e40af; }
      h2 { font-size: 15px; font-weight: 600; margin: 20px 0 8px; color: #374151; border-bottom: 1px solid #e5e7eb; padding-bottom: 4px; }
      .meta { font-size: 11px; color: #9ca3af; margin-bottom: 24px; }
      table { width: 100%; border-collapse: collapse; margin-bottom: 16px; font-size: 12px; }
      th { background: #eff6ff; color: #1e40af; font-weight: 600; padding: 7px 10px; text-align: left; border-bottom: 2px solid #bfdbfe; }
      td { padding: 6px 10px; border-bottom: 1px solid #f3f4f6; }
      tr:nth-child(even) td { background: #f9fafb; }
      .green { color: #16a34a; font-weight: 600; }
      .red   { color: #dc2626; font-weight: 600; }
      .badge { display: inline-block; padding: 1px 8px; border-radius: 9999px; font-size: 10px; font-weight: 600; background: #dbeafe; color: #1e40af; }
      .footer { margin-top: 32px; font-size: 10px; color: #9ca3af; text-align: center; border-top: 1px solid #e5e7eb; padding-top: 12px; }
      @media print { body { padding: 16px; } }
    </style>
  </head><body>${htmlContent}<div class="footer">Generated by StockVision · ${new Date().toLocaleDateString('en-IN')} · Not SEBI registered · Not financial advice</div></body></html>`);
  win.document.close();
  setTimeout(() => { win.print(); win.close(); }, 300);
}

// ── Preset export types ───────────────────────────────────────────────────
export function exportWatchlist(watchlists) {
  const rows = [];
  watchlists.forEach(wl => {
    (wl.stocks || []).forEach(s => {
      rows.push([wl.name, s.symbol, s.name || '', s.currentPrice || '', s.dayChange || '', s.dayChangePercent || '']);
    });
  });
  exportCSV('stockvision_watchlist.csv',
    ['Watchlist', 'Symbol', 'Company', 'Current Price (₹)', 'Day Change (₹)', 'Day Change (%)'],
    rows
  );
}

export function exportFinancials(symbol, financials) {
  if (!financials) return;
  const { annualPL } = financials;
  if (!annualPL?.length) return;
  const headers = ['Metric', ...annualPL.map(y => y.date || y.year)];
  const metrics = ['revenue', 'grossProfit', 'operatingIncome', 'netIncome', 'eps'];
  const rows = metrics.map(m => [m, ...annualPL.map(y => y[m] ?? '')]);
  exportCSV(`${symbol}_financials.csv`, headers, rows);
}

export function exportSIPPlan(params, timeline) {
  const rows = timeline.map(d => [d.year, Math.round(d.invested), Math.round(d.value), Math.round(d.gains)]);
  exportCSV('sip_plan.csv', ['Year', 'Total Invested (₹)', 'Portfolio Value (₹)', 'Gains (₹)'], rows);
}

export function exportStockPDF(stock, ratios, financials) {
  const price = stock?.currentPrice ?? '—';
  const change = stock?.dayChangePercent ?? 0;
  const chgClass = change >= 0 ? 'green' : 'red';
  const chgSign  = change >= 0 ? '+' : '';

  const ratioRows = [
    ['P/E Ratio', ratios?.trailingPE?.toFixed(2) ?? '—'],
    ['P/B Ratio', ratios?.priceToBook?.toFixed(2) ?? '—'],
    ['EPS (TTM)', ratios?.trailingEps?.toFixed(2) ?? '—'],
    ['ROE', ratios?.returnOnEquity ? (ratios.returnOnEquity * 100).toFixed(1) + '%' : '—'],
    ['Debt/Equity', ratios?.debtToEquity?.toFixed(2) ?? '—'],
    ['Dividend Yield', ratios?.dividendYield ? (ratios.dividendYield * 100).toFixed(2) + '%' : '—'],
    ['Beta', ratios?.beta?.toFixed(2) ?? '—'],
    ['Market Cap', ratios?.marketCap ? '₹' + (ratios.marketCap / 1e7).toFixed(0) + ' Cr' : '—'],
  ];

  const html = `
    <h1>${stock?.name || stock?.symbol || 'Stock'} — StockVision Report</h1>
    <div class="meta">Symbol: ${stock?.symbol} · Generated: ${new Date().toLocaleDateString('en-IN')} · Data source: Yahoo Finance</div>

    <h2>📈 Price Summary</h2>
    <table>
      <tr><th>Current Price</th><th>Day Change</th><th>52W High</th><th>52W Low</th><th>Volume</th></tr>
      <tr>
        <td><strong>₹${price}</strong></td>
        <td class="${chgClass}">${chgSign}${change?.toFixed ? change.toFixed(2) : change}%</td>
        <td>₹${stock?.fiftyTwoWeekHigh ?? '—'}</td>
        <td>₹${stock?.fiftyTwoWeekLow ?? '—'}</td>
        <td>${stock?.volume?.toLocaleString('en-IN') ?? '—'}</td>
      </tr>
    </table>

    <h2>💰 Key Ratios & Fundamentals</h2>
    <table>
      <tr><th>Metric</th><th>Value</th></tr>
      ${ratioRows.map(([k, v]) => `<tr><td>${k}</td><td>${v}</td></tr>`).join('')}
    </table>

    <p style="font-size:11px;color:#9ca3af;margin-top:16px;">⚠️ Past performance does not guarantee future results. This report is for educational purposes only.</p>
  `;
  exportPDF(`${stock?.symbol} Report — StockVision`, html);
}

// ── The reusable ExportButton component ───────────────────────────────────
export default function ExportButton({
  onExportPDF,
  onExportCSV,
  label = 'Export',
  darkMode,
  size = 'sm',
}) {
  const [open, setOpen] = useState(false);

  const btn = darkMode
    ? 'bg-gray-800 border-gray-700 text-gray-300 hover:bg-gray-700'
    : 'bg-white border-gray-200 text-gray-700 hover:bg-gray-50';

  const dd = darkMode
    ? 'bg-gray-800 border-gray-700 text-gray-200'
    : 'bg-white border-gray-200 text-gray-800';

  const ddItem = darkMode
    ? 'hover:bg-gray-700'
    : 'hover:bg-gray-50';

  const szCls = size === 'sm' ? 'text-xs px-3 py-1.5' : 'text-sm px-4 py-2';

  return (
    <div className="relative">
      <button
        onClick={() => setOpen(o => !o)}
        className={`flex items-center gap-1.5 rounded-lg border font-medium transition-colors ${btn} ${szCls}`}>
        <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
        </svg>
        {label}
        <svg className={`w-3 h-3 transition-transform ${open ? 'rotate-180' : ''}`} fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
        </svg>
      </button>

      {open && (
        <>
          <div className="fixed inset-0 z-40" onClick={() => setOpen(false)} />
          <div className={`absolute right-0 top-full mt-1 w-44 rounded-xl border shadow-lg z-50 overflow-hidden ${dd}`}>
            {onExportPDF && (
              <button onClick={() => { onExportPDF(); setOpen(false); }}
                className={`w-full flex items-center gap-2 px-3 py-2.5 text-sm transition-colors ${ddItem}`}>
                <span>📄</span> Export PDF
              </button>
            )}
            {onExportCSV && (
              <button onClick={() => { onExportCSV(); setOpen(false); }}
                className={`w-full flex items-center gap-2 px-3 py-2.5 text-sm transition-colors ${ddItem}`}>
                <span>📊</span> Export CSV/Excel
              </button>
            )}
            <button onClick={() => { window.print(); setOpen(false); }}
              className={`w-full flex items-center gap-2 px-3 py-2.5 text-sm transition-colors ${ddItem}`}>
              <span>🖨️</span> Print Page
            </button>
          </div>
        </>
      )}
    </div>
  );
}
