// utils/ipoFetcher.js — IPO Data Fetcher
// Phase 6 Month 33 — Fetches IPO info, GMP, allotment data
// JAI SHREE GANESH 🙏

let yahooFinance = null;
try {
  const mod = require('yahoo-finance2');
  yahooFinance = mod.default || mod;
} catch (e) {
  console.warn('[ipoFetcher] yahoo-finance2 unavailable:', e.message);
}

// ─── Static IPO Database (Recent & Upcoming Indian IPOs) ─────────────────────
// In production this would be fetched from NSE/BSE APIs or scraped
const STATIC_IPOS = [
  {
    id: 'hyundai-india-2024',
    company: 'Hyundai Motor India',
    symbol: 'HYUNDAI.NS',
    sector: 'Automobile',
    subsector: 'Passenger Vehicles',
    status: 'listed',
    issueType: 'Book Built',
    priceRange: { low: 1865, high: 1960 },
    issuePrice: 1960,
    issueSize: 27870,  // crores
    freshIssue: 0,
    ofs: 27870,
    lotSize: 7,
    minInvestment: 13720,
    openDate: '2024-10-15',
    closeDate: '2024-10-17',
    allotmentDate: '2024-10-18',
    listingDate: '2024-10-22',
    listingPrice: 1931,
    listingGain: -1.48,
    cmp: 1920,
    promoterHolding: 82.5,
    subscriptionTotal: 2.37,
    subscriptionQIB: 6.97,
    subscriptionNII: 0.60,
    subscriptionRetail: 0.50,
    registrar: 'Kfin Technologies',
    lead_managers: ['Kotak Mahindra Capital', 'Citigroup', 'HSBC', 'JP Morgan', 'Morgan Stanley'],
    use_of_proceeds: 'OFS — proceeds go to selling shareholders',
    gmp: -40,
    allotmentLink: 'https://kfintech.com',
    drhpLink: '#',
    financials: {
      revenue: [66380, 71302, 69829],  // crores, last 3 years
      pat: [4709, 4653, 6060],
      eps: [58.8, 58.1, 75.7],
      pe: 25.9,
      roe: 26.0,
      roce: 30.7,
      debtEquity: 0.04,
    },
    peers: [
      { name: 'Maruti Suzuki', pe: 28.1, roe: 18.7 },
      { name: 'M&M', pe: 32.4, roe: 20.1 },
      { name: 'Tata Motors', pe: 9.8, roe: 32.0 },
    ],
    description: 'Hyundai Motor India Ltd is a wholly owned subsidiary of Hyundai Motor Company, South Korea. It is the second largest car manufacturer in India by sales.',
    strengths: ['Strong brand, 2nd largest passenger vehicle OEM in India', 'Diverse product portfolio across segments', 'Strong R&D and EV pipeline'],
    risks: ['High OFS — no fresh capital raised', 'Competition from Maruti, Tata', 'High valuation vs peers at listing', 'EV transition risks'],
    badge: 'Recent',
    badgeColor: 'blue',
  },
  {
    id: 'bajaj-housing-2024',
    company: 'Bajaj Housing Finance',
    symbol: 'BAJAJHFL.NS',
    sector: 'NBFC / Finance',
    subsector: 'Housing Finance',
    status: 'listed',
    issueType: 'Book Built',
    priceRange: { low: 66, high: 70 },
    issuePrice: 70,
    issueSize: 6560,
    freshIssue: 3560,
    ofs: 3000,
    lotSize: 214,
    minInvestment: 14980,
    openDate: '2024-09-09',
    closeDate: '2024-09-11',
    allotmentDate: '2024-09-12',
    listingDate: '2024-09-16',
    listingPrice: 150,
    listingGain: 114.29,
    cmp: 115,
    promoterHolding: 88.75,
    subscriptionTotal: 67.43,
    subscriptionQIB: 209.36,
    subscriptionNII: 43.39,
    subscriptionRetail: 7.13,
    registrar: 'Kfin Technologies',
    lead_managers: ['Kotak Mahindra Capital', 'BofA Securities', 'Axis Capital', 'Goldman Sachs', 'SBI Capital'],
    use_of_proceeds: 'Fresh issue proceeds for augmenting capital base',
    gmp: 12,
    allotmentLink: 'https://kfintech.com',
    drhpLink: '#',
    financials: {
      revenue: [4847, 6384, 7709],
      pat: [1258, 1731, 2119],
      eps: [1.5, 2.1, 2.6],
      pe: 26.9,
      roe: 14.2,
      roce: 11.3,
      debtEquity: 5.8,
    },
    peers: [
      { name: 'LIC Housing Finance', pe: 8.1, roe: 13.2 },
      { name: 'PNB Housing Finance', pe: 15.3, roe: 12.0 },
      { name: 'Can Fin Homes', pe: 13.4, roe: 18.9 },
    ],
    description: 'Bajaj Housing Finance Limited is a non-deposit taking housing finance company, registered with NHB. It offers mortgage loans to individuals and corporate entities.',
    strengths: ['Bajaj brand parentage', 'Low NPA ratios vs peers', 'Strong AUM growth 30%+ CAGR', 'Robust underwriting standards'],
    risks: ['Highly competitive housing finance sector', 'Interest rate sensitivity', 'High valuation post listing'],
    badge: 'Blockbuster',
    badgeColor: 'green',
  },
  {
    id: 'ola-electric-2024',
    company: 'Ola Electric Mobility',
    symbol: 'OLAELEC.NS',
    sector: 'EV / Automobile',
    subsector: 'Electric Vehicles',
    status: 'listed',
    issueType: 'Book Built',
    priceRange: { low: 72, high: 76 },
    issuePrice: 76,
    issueSize: 6146,
    freshIssue: 5500,
    ofs: 646,
    lotSize: 197,
    minInvestment: 14972,
    openDate: '2024-08-02',
    closeDate: '2024-08-06',
    allotmentDate: '2024-08-07',
    listingDate: '2024-08-09',
    listingPrice: 75.99,
    listingGain: -0.01,
    cmp: 60,
    promoterHolding: 34.9,
    subscriptionTotal: 4.27,
    subscriptionQIB: 5.17,
    subscriptionNII: 3.93,
    subscriptionRetail: 3.92,
    registrar: 'Kfin Technologies',
    lead_managers: ['Kotak Mahindra Capital', 'Goldman Sachs', 'BofA Securities', 'Axis Capital', 'ICICI Securities'],
    use_of_proceeds: 'Capex for Gigafactory expansion, R&D, repayment of debt',
    gmp: -15,
    allotmentLink: 'https://kfintech.com',
    drhpLink: '#',
    financials: {
      revenue: [456, 2630, 5010],
      pat: [-784, -1472, -1584],
      eps: [-2.4, -4.4, -4.9],
      pe: null,
      roe: null,
      roce: null,
      debtEquity: 2.1,
    },
    peers: [
      { name: 'Hero MotoCorp', pe: 21.4, roe: 24.3 },
      { name: 'Bajaj Auto', pe: 26.8, roe: 27.0 },
      { name: 'TVS Motor', pe: 47.2, roe: 24.6 },
    ],
    description: 'Ola Electric is India\'s largest EV manufacturer by market share in the electric 2-wheeler segment, operating the Ola Futurefactory — the world\'s largest 2-wheeler facility.',
    strengths: ['Market leader in EV 2-wheelers (30%+ share)', 'Integrated manufacturing with Gigafactory', 'Tech-first approach with OTA updates', 'Strong brand recognition'],
    risks: ['Consistently loss-making — no clear path to profitability', 'High warranty claims & service quality issues', 'Intense competition from established players', 'Regulatory and subsidy risk'],
    badge: 'Disappointing',
    badgeColor: 'red',
  },
  {
    id: 'ntpc-green-2024',
    company: 'NTPC Green Energy',
    symbol: 'NTPCGREEN.NS',
    sector: 'Power / Renewable Energy',
    subsector: 'Renewable Energy',
    status: 'listed',
    issueType: 'Book Built',
    priceRange: { low: 102, high: 108 },
    issuePrice: 108,
    issueSize: 10000,
    freshIssue: 10000,
    ofs: 0,
    lotSize: 138,
    minInvestment: 14904,
    openDate: '2024-11-19',
    closeDate: '2024-11-22',
    allotmentDate: '2024-11-25',
    listingDate: '2024-11-27',
    listingPrice: 111.5,
    listingGain: 3.24,
    cmp: 105,
    promoterHolding: 94.39,
    subscriptionTotal: 2.55,
    subscriptionQIB: 3.62,
    subscriptionNII: 1.69,
    subscriptionRetail: 1.83,
    registrar: 'KFin Technologies',
    lead_managers: ['ICICI Securities', 'HDFC Bank', 'IIFL Securities', 'Nuvama Wealth'],
    use_of_proceeds: 'Equity contribution to subsidiaries for renewable projects, general corporate purposes',
    gmp: -3,
    allotmentLink: 'https://kfintech.com',
    drhpLink: '#',
    financials: {
      revenue: [1962, 2457, 2868],
      pat: [344, 485, 540],
      eps: [0.5, 0.7, 0.8],
      pe: 135,
      roe: 6.4,
      roce: 7.1,
      debtEquity: 2.6,
    },
    peers: [
      { name: 'Adani Green', pe: 245, roe: 14.2 },
      { name: 'Tata Power', pe: 37.8, roe: 9.8 },
      { name: 'JSW Energy', pe: 47.3, roe: 12.1 },
    ],
    description: 'NTPC Green Energy Limited is a wholly owned subsidiary of NTPC Ltd, focusing on renewable energy. It aims to achieve 60GW renewable energy capacity by 2032.',
    strengths: ['NTPC brand — Navratna PSU', 'Strong growth targets in renewables', 'Govt backing and policy tailwinds', 'Established project pipeline'],
    risks: ['Very high PE valuation for a loss-at-nascent stage entity', 'Long gestation period for renewable projects', 'Parent NTPC already listed', 'Interest rate risk on heavy debt'],
    badge: 'PSU',
    badgeColor: 'orange',
  },
  {
    id: 'swiggy-2024',
    company: 'Swiggy',
    symbol: 'SWIGGY.NS',
    sector: 'Food Delivery / Tech',
    subsector: 'Quick Commerce',
    status: 'listed',
    issueType: 'Book Built',
    priceRange: { low: 371, high: 390 },
    issuePrice: 390,
    issueSize: 11327,
    freshIssue: 4499,
    ofs: 6828,
    lotSize: 38,
    minInvestment: 14820,
    openDate: '2024-11-06',
    closeDate: '2024-11-08',
    allotmentDate: '2024-11-11',
    listingDate: '2024-11-13',
    listingPrice: 412,
    listingGain: 5.64,
    cmp: 340,
    promoterHolding: 0,
    subscriptionTotal: 3.59,
    subscriptionQIB: 6.09,
    subscriptionNII: 2.54,
    subscriptionRetail: 1.14,
    registrar: 'Link Intime India',
    lead_managers: ['Kotak Mahindra Capital', 'BofA Securities', 'Jefferies', 'ICICI Securities', 'Avendus'],
    use_of_proceeds: 'Instamart dark store expansion, tech infra, marketing, debt repayment',
    gmp: -20,
    allotmentLink: 'https://linkintime.co.in',
    drhpLink: '#',
    financials: {
      revenue: [6119, 8265, 11247],
      pat: [-3629, -4179, -2350],
      eps: [-6.4, -7.4, -4.0],
      pe: null,
      roe: null,
      roce: null,
      debtEquity: 0.3,
    },
    peers: [
      { name: 'Zomato', pe: 250, roe: 3.2 },
      { name: 'Nykaa', pe: 72, roe: 4.1 },
      { name: 'Paytm', pe: null, roe: null },
    ],
    description: 'Swiggy is India\'s leading food delivery and quick commerce platform, operating Swiggy Food Delivery, Instamart (10-minute grocery), Dineout and Genie.',
    strengths: ['#1 or #2 in food delivery & quick commerce', 'Rapidly growing Instamart business', 'Strong brand and network of restaurants', 'Large TAM in food & grocery delivery'],
    risks: ['Consistently loss-making over 10 years', 'Intense competition from Zomato, Blinkit', 'Unit economics still negative in new markets', 'Quick commerce requires massive capex'],
    badge: 'Startup',
    badgeColor: 'violet',
  },
  {
    id: 'mobikwik-2024',
    company: 'MobiKwik Systems',
    symbol: 'MOBIKWIK.NS',
    sector: 'Fintech',
    subsector: 'Digital Payments & Lending',
    status: 'listed',
    issueType: 'Book Built',
    priceRange: { low: 235, high: 247 },
    issuePrice: 247,
    issueSize: 572,
    freshIssue: 572,
    ofs: 0,
    lotSize: 60,
    minInvestment: 14820,
    openDate: '2024-12-11',
    closeDate: '2024-12-13',
    allotmentDate: '2024-12-16',
    listingDate: '2024-12-18',
    listingPrice: 440,
    listingGain: 78.14,
    cmp: 480,
    promoterHolding: 19.3,
    subscriptionTotal: 119.89,
    subscriptionQIB: 125.51,
    subscriptionNII: 164.60,
    subscriptionRetail: 90.13,
    registrar: 'Link Intime India',
    lead_managers: ['SBI Capital Markets', 'Dam Capital Advisors'],
    use_of_proceeds: 'Buy Now Pay Later (BNPL) portfolio growth, payment infrastructure expansion',
    gmp: 185,
    allotmentLink: 'https://linkintime.co.in',
    drhpLink: '#',
    financials: {
      revenue: [187, 507, 875],
      pat: [-83, -83, 14],
      eps: [-3.8, -3.8, 0.6],
      pe: null,
      roe: null,
      roce: null,
      debtEquity: 1.9,
    },
    peers: [
      { name: 'Paytm', pe: null, roe: null },
      { name: 'One97 Comm', pe: null, roe: null },
      { name: 'Nykaa', pe: 72, roe: 4.1 },
    ],
    description: 'MobiKwik is India\'s leading digital payment platform with Buy Now Pay Later (Zip) as a key product, serving 140M+ users and 4M+ merchants.',
    strengths: ['Achieved profitability in FY24', 'Strong BNPL growth — Zip product', 'Large user base 140M+', 'Diversified product portfolio'],
    risks: ['Fintech regulatory uncertainty', 'Competition from PhonePe, Paytm, Google Pay', 'BNPL credit quality risk', 'Thin margins in payments'],
    badge: 'Strong Listing',
    badgeColor: 'green',
  },
  {
    id: 'vishal-mega-mart-2024',
    company: 'Vishal Mega Mart',
    symbol: 'VISHALMEGA.NS',
    sector: 'Retail',
    subsector: 'Value Retail',
    status: 'listed',
    issueType: 'Book Built',
    priceRange: { low: 74, high: 78 },
    issuePrice: 78,
    issueSize: 8000,
    freshIssue: 0,
    ofs: 8000,
    lotSize: 192,
    minInvestment: 14976,
    openDate: '2024-12-11',
    closeDate: '2024-12-13',
    allotmentDate: '2024-12-16',
    listingDate: '2024-12-18',
    listingPrice: 98,
    listingGain: 25.64,
    cmp: 95,
    promoterHolding: 0,
    subscriptionTotal: 27.29,
    subscriptionQIB: 46.95,
    subscriptionNII: 23.21,
    subscriptionRetail: 8.87,
    registrar: 'Kfin Technologies',
    lead_managers: ['Goldman Sachs', 'Morgan Stanley', 'JM Financial', 'ICICI Securities'],
    use_of_proceeds: 'OFS — proceeds to PE investor Kedaara Capital',
    gmp: 18,
    allotmentLink: 'https://kfintech.com',
    drhpLink: '#',
    financials: {
      revenue: [6240, 7618, 8911],
      pat: [211, 303, 461],
      eps: [0.9, 1.3, 2.0],
      pe: 39,
      roe: 14.6,
      roce: 18.9,
      debtEquity: 0.1,
    },
    peers: [
      { name: 'Avenue Supermarts (DMart)', pe: 96, roe: 16.3 },
      { name: 'Trent', pe: 145, roe: 28.4 },
      { name: 'ABFRL', pe: null, roe: null },
    ],
    description: 'Vishal Mega Mart operates value retail stores across India, offering apparel, FMCG and general merchandise. It has 645+ stores across 414 cities.',
    strengths: ['Value retail focused on price-sensitive customers', 'Strong pan-India presence in Tier 2/3 cities', 'Consistent profitability & cash generation', 'Low debt balance sheet'],
    risks: ['Pure OFS — no fresh capital', 'PE-backed exit overhang', 'Competition from DMart, Reliance Retail, Meesho', 'Thin retail margins'],
    badge: 'Good Listing',
    badgeColor: 'green',
  },
  // Upcoming IPOs
  {
    id: 'lg-electronics-2025',
    company: 'LG Electronics India',
    symbol: null,
    sector: 'Consumer Electronics',
    subsector: 'Home Appliances & TV',
    status: 'upcoming',
    issueType: 'Book Built',
    priceRange: { low: null, high: null },
    issuePrice: null,
    issueSize: 15000, // estimated
    freshIssue: 0,
    ofs: 15000,
    lotSize: null,
    minInvestment: null,
    openDate: '2025-03-15',
    closeDate: '2025-03-17',
    allotmentDate: '2025-03-18',
    listingDate: '2025-03-21',
    listingPrice: null,
    listingGain: null,
    cmp: null,
    promoterHolding: 82.0,
    subscriptionTotal: null,
    subscriptionQIB: null,
    subscriptionNII: null,
    subscriptionRetail: null,
    registrar: 'Kfin Technologies',
    lead_managers: ['Goldman Sachs', 'JP Morgan', 'ICICI Securities'],
    use_of_proceeds: 'OFS — proceeds to LG Electronics Co., South Korea',
    gmp: 95,
    allotmentLink: null,
    drhpLink: '#',
    financials: {
      revenue: [17780, 20230, 23400],
      pat: [480, 644, 820],
      eps: [7.2, 9.7, 12.4],
      pe: 45,  // estimated at issue price
      roe: 21.3,
      roce: 25.7,
      debtEquity: 0.0,
    },
    peers: [
      { name: 'Whirlpool India', pe: 31.2, roe: 14.1 },
      { name: 'Havells India', pe: 68.4, roe: 22.7 },
      { name: 'Blue Star', pe: 58.7, roe: 23.4 },
    ],
    description: 'LG Electronics India is the Indian subsidiary of South Korean MNC LG Electronics, market leader in washing machines, refrigerators and OLED TVs in India.',
    strengths: ['Market leader in premium home appliances', 'Strong brand trust 25+ years in India', 'Extensive service network', 'Debt-free balance sheet'],
    risks: ['Pure OFS — parent selling stake', 'Competition from Samsung, Voltas, Haier', 'Currency and import duty risks', 'Discretionary consumer spend slowdown risk'],
    badge: 'Upcoming',
    badgeColor: 'amber',
  },
  {
    id: 'tata-capital-2025',
    company: 'Tata Capital Financial Services',
    symbol: null,
    sector: 'NBFC / Finance',
    subsector: 'Diversified Financial Services',
    status: 'upcoming',
    issueType: 'Book Built',
    priceRange: { low: null, high: null },
    issuePrice: null,
    issueSize: 17000, // estimated
    freshIssue: 17000,
    ofs: 0,
    lotSize: null,
    minInvestment: null,
    openDate: '2025-04-10',
    closeDate: '2025-04-12',
    allotmentDate: '2025-04-15',
    listingDate: '2025-04-17',
    listingPrice: null,
    listingGain: null,
    cmp: null,
    promoterHolding: 93.0,
    subscriptionTotal: null,
    subscriptionQIB: null,
    subscriptionNII: null,
    subscriptionRetail: null,
    registrar: 'Link Intime India',
    lead_managers: ['Kotak Mahindra Capital', 'BofA Securities', 'Citigroup'],
    use_of_proceeds: 'Augmenting capital base for lending business growth',
    gmp: 210,
    allotmentLink: null,
    drhpLink: '#',
    financials: {
      revenue: [12880, 15430, 19200],
      pat: [3120, 3840, 5100],
      eps: [8.4, 10.3, 13.7],
      pe: 32,
      roe: 15.2,
      roce: 11.8,
      debtEquity: 5.4,
    },
    peers: [
      { name: 'Bajaj Finance', pe: 32.4, roe: 22.1 },
      { name: 'Cholamandalam', pe: 28.7, roe: 18.4 },
      { name: 'Shriram Finance', pe: 14.2, roe: 16.8 },
    ],
    description: 'Tata Capital is the financial services arm of the Tata Group, offering home loans, personal loans, business finance and wealth management across India.',
    strengths: ['Tata brand — highest trust in India', 'Diversified lending book', 'Growing retail loan segment', 'Strong risk management culture'],
    risks: ['NBFC regulatory and liquidity risks', 'Credit cycle risk if economy slows', 'Competition from banks and Bajaj Finance', 'IPO valuation likely at premium'],
    badge: 'Highly Awaited',
    badgeColor: 'green',
  },
  {
    id: 'nsdl-2025',
    company: 'National Securities Depository (NSDL)',
    symbol: null,
    sector: 'Capital Markets',
    subsector: 'Depository Services',
    status: 'upcoming',
    issueType: 'Book Built',
    priceRange: { low: null, high: null },
    issuePrice: null,
    issueSize: 3000,
    freshIssue: 0,
    ofs: 3000,
    lotSize: null,
    minInvestment: null,
    openDate: '2025-03-25',
    closeDate: '2025-03-27',
    allotmentDate: '2025-03-28',
    listingDate: '2025-04-01',
    listingPrice: null,
    listingGain: null,
    cmp: null,
    promoterHolding: null,
    subscriptionTotal: null,
    subscriptionQIB: null,
    subscriptionNII: null,
    subscriptionRetail: null,
    registrar: 'KFin Technologies',
    lead_managers: ['ICICI Securities', 'HDFC Bank', 'IIFL Securities'],
    use_of_proceeds: 'OFS by existing shareholders IDBI, NSE, SBI, HDFC Bank, Union Bank',
    gmp: 310,
    allotmentLink: null,
    drhpLink: '#',
    financials: {
      revenue: [1041, 1231, 1407],
      pat: [434, 497, 597],
      eps: [4.3, 4.9, 5.9],
      pe: 52,
      roe: 22.1,
      roce: 24.8,
      debtEquity: 0.0,
    },
    peers: [
      { name: 'CDSL', pe: 55.2, roe: 27.3 },
      { name: 'BSE Ltd', pe: 72.4, roe: 18.4 },
      { name: 'MCX', pe: 42.1, roe: 31.2 },
    ],
    description: 'NSDL is the first and largest depository in India, holding over ₹355 lakh crore worth of securities in demat form. It processes trillions in transactions annually.',
    strengths: ['Quasi-monopoly infrastructure in capital markets', 'Highest demat account AUC in India', 'Zero debt, high margins', 'Duopoly with CDSL — high barriers to entry'],
    risks: ['Regulatory risk — SEBI oversight', 'Growth dependent on new demat account additions', 'CDSL gaining market share with discount brokers'],
    badge: 'Infrastructure',
    badgeColor: 'blue',
  },
];

// ─── Compute allotment probability based on subscription ──────────────────────
function allotmentProbability(sub) {
  if (!sub || sub < 1) return { prob: 100, label: 'Guaranteed', color: 'green', tips: 'IPO undersubscribed. All applicants get allotment.' };
  if (sub < 2)   return { prob: 95,  label: 'Very High', color: 'green', tips: 'Very low oversubscription. Most applicants likely to get shares.' };
  if (sub < 5)   return { prob: 70,  label: 'High', color: 'lime', tips: 'Moderately subscribed. Apply from multiple family accounts.' };
  if (sub < 15)  return { prob: 35,  label: 'Moderate', color: 'yellow', tips: 'Oversubscribed. Apply at cutoff price. Use multiple demat accounts.' };
  if (sub < 50)  return { prob: 12,  label: 'Low', color: 'orange', tips: 'Heavily subscribed. Multiple applications from family members recommended.' };
  if (sub < 100) return { prob: 4,   label: 'Very Low', color: 'red', tips: 'Very oversubscribed. Consider NII (Non-Institutional) category if investing ₹2L+.' };
  return { prob: 1, label: 'Lottery', color: 'red', tips: 'Lottery-level odds. Only apply if strong conviction on listing gains. Use HNI (NII) category for better odds.' };
}

// ─── GMP Confidence Estimate ─────────────────────────────────────────────────
function gmpAnalysis(gmp, issuePrice) {
  if (!gmp || !issuePrice) return null;
  const gmpPercent = +((gmp / issuePrice) * 100).toFixed(1);
  let sentiment, confidence, interpretation;

  if (gmpPercent > 40)      { sentiment = '🚀 Exceptional'; confidence = 'High Demand'; interpretation = `GMP of ₹${gmp} (${gmpPercent}%) indicates blockbuster listing expected. Strong retail demand.`; }
  else if (gmpPercent > 20) { sentiment = '🟢 Strong';      confidence = 'Good Demand';  interpretation = `GMP of ₹${gmp} (${gmpPercent}%) signals healthy demand. Decent listing gain expected.`; }
  else if (gmpPercent > 5)  { sentiment = '🟡 Positive';    confidence = 'Mild Demand';  interpretation = `GMP of ₹${gmp} (${gmpPercent}%) shows mild positive sentiment. Modest listing gains likely.`; }
  else if (gmpPercent > -5) { sentiment = '⚪ Flat';        confidence = 'Neutral';       interpretation = `GMP of ₹${gmp} (${gmpPercent}%) near issue price. Flat listing expected.`; }
  else if (gmpPercent > -20){ sentiment = '🟠 Weak';        confidence = 'Weak Demand';   interpretation = `GMP of ₹${gmp} (${gmpPercent}%) shows weak sentiment. Listing at discount likely.`; }
  else                       { sentiment = '🔴 Negative';   confidence = 'Poor Demand';   interpretation = `GMP of ₹${gmp} (${gmpPercent}%) shows significant negative premium. Avoid for listing gains.`; }

  return { gmp, gmpPercent, sentiment, confidence, interpretation };
}

// ─── IPO Performance History ─────────────────────────────────────────────────
function ipoPerformanceStats() {
  const listed = STATIC_IPOS.filter(i => i.status === 'listed' && i.listingGain !== null);
  const positive = listed.filter(i => i.listingGain > 0);
  const negative = listed.filter(i => i.listingGain < 0);
  const avgGain = +(listed.reduce((s, i) => s + i.listingGain, 0) / listed.length).toFixed(1);
  const best  = listed.reduce((b, i) => i.listingGain > b.listingGain ? i : b, listed[0]);
  const worst = listed.reduce((w, i) => i.listingGain < w.listingGain ? i : w, listed[0]);

  return {
    total: listed.length,
    positiveListings: positive.length,
    negativeListings: negative.length,
    hitRate: +((positive.length / listed.length) * 100).toFixed(1),
    avgListingGain: avgGain,
    best: { company: best.company, gain: best.listingGain },
    worst: { company: worst.company, gain: worst.listingGain },
  };
}

// ─── Live Price Enrichment ────────────────────────────────────────────────────
async function enrichWithLivePrice(ipo) {
  if (!ipo.symbol || ipo.status !== 'listed') return ipo;
  try {
    if (!yahooFinance) throw new Error("yahoo-finance2 not available");
    const quote = await yahooFinance.quote(ipo.symbol, {}, { validateResult: false });
    if (quote && quote.regularMarketPrice) {
      const cmp = +quote.regularMarketPrice.toFixed(2);
      const currentGain = ipo.issuePrice ? +(((cmp - ipo.issuePrice) / ipo.issuePrice) * 100).toFixed(1) : null;
      const fromListing = ipo.listingPrice ? +(((cmp - ipo.listingPrice) / ipo.listingPrice) * 100).toFixed(1) : null;
      return { ...ipo, cmp, currentGain, gainFromListing: fromListing };
    }
  } catch (e) { /* silent fail */ }
  return { ...ipo, currentGain: ipo.issuePrice && ipo.cmp ? +(((ipo.cmp - ipo.issuePrice) / ipo.issuePrice) * 100).toFixed(1) : null };
}

// ─── Exports ─────────────────────────────────────────────────────────────────
module.exports = {
  STATIC_IPOS,
  allotmentProbability,
  gmpAnalysis,
  ipoPerformanceStats,
  enrichWithLivePrice,
};
